import { LeagueModel, LeaguesPayload } from './models/index';

export const leagues2015: LeagueModel[] = [
  // Spain
  {
    countryId: '1',
    name: 'La Liga',
    code: 'LL',
    id: '1',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/LaLiga.svg/1200px-LaLiga.svg.png',
  },
  {
    countryId: '1',
    name: 'Segunda División',
    code: 'SD',
    id: '2',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/92/LaLiga2.svg/1200px-LaLiga2.svg.png',
  },
  {
    countryId: '1',
    name: 'Segunda División B',
    code: 'SDB',
    id: '3',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Segunda_Divisi%C3%B3n_B_logo.svg/1200px-Segunda_Divisi%C3%B3n_B_logo.svg.png',
  },
  // England
  {
    countryId: '2',
    name: 'Premier League',
    code: 'PL',
    id: '4',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Premier_League_Logo.svg/1200px-Premier_League_Logo.svg.png',
  },
  {
    countryId: '2',
    name: 'EFL Championship',
    code: 'EFL',
    id: '5',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/86/EFL_Championship.svg/1200px-EFL_Championship.svg.png',
  },
  {
    countryId: '2',
    name: 'EFL League One',
    code: 'L1',
    id: '6',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/82/EFL_League_One.svg/1200px-EFL_League_One.svg.png',
  },
  // Italy
  {
    countryId: '3',
    name: 'Serie A',
    code: 'SA',
    id: '7',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Serie_A_logo_%282019%29.svg/1200px-Serie_A_logo_%282019%29.svg.png',
  },
  {
    countryId: '3',
    name: 'Serie B',
    code: 'SB',
    id: '8',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Serie_B_Logo.svg/1200px-Serie_B_Logo.svg.png',
  },
  {
    countryId: '3',
    name: 'Serie C',
    code: 'SC',
    id: '9',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Serie_C_logo.svg/1200px-Serie_C_logo.svg.png',
  },
  // Croatia
  {
    countryId: '4',
    name: 'Prva HNL',
    code: '1HNL',
    id: '10',
    image: 'https://upload.wikimedia.org/wikipedia/en/4/47/Prva_HNL_logo.png',
  },
  {
    countryId: '4',
    name: 'Druga HNL',
    code: '2HNL',
    id: '11',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/64/Druga_HNL_logo.svg/1200px-Druga_HNL_logo.svg.png',
  },
  {
    countryId: '4',
    name: 'Treća HNL',
    code: '3HNL',
    id: '12',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Tre%C4%87a_HNL_logo.svg/1200px-Tre%C4%87a_HNL_logo.svg.png',
  },
  // Cyprus
  {
    countryId: '5',
    name: 'Cypriot First Division',
    code: 'CFD',
    id: '13',
    image: 'https://upload.wikimedia.org/wikipedia/en/e/e3/Cypriot_First_Division_logo.png',
  },
  {
    countryId: '5',
    name: 'Cypriot Second Division',
    code: 'CSD',
    id: '14',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Cypriot_Second_Division_logo.svg/1200px-Cypriot_Second_Division_logo.svg.png',
  },
  {
    countryId: '5',
    name: 'Cypriot Third Division',
    code: 'CTD',
    id: '15',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Cypriot_Third_Division_logo.svg/1200px-Cypriot_Third_Division_logo.svg.png',
  },
  // Czech Republic
  {
    countryId: '6',
    name: 'Czech First League',
    code: 'CFL',
    id: '16',
    image: 'https://upload.wikimedia.org/wikipedia/en/7/7c/Fortuna_liga_logo.png',
  },
  {
    countryId: '6',
    name: 'Czech National Football League',
    code: 'CNFL',
    id: '17',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Czech_National_Football_League_logo.svg/1200px-Czech_National_Football_League_logo.svg.png',
  },
  {
    countryId: '6',
    name: 'Czech Third Division',
    code: 'CTD',
    id: '18',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/72/Czech_Third_Division_logo.svg/1200px-Czech_Third_Division_logo.svg.png',
  },
  // Denmark
  {
    countryId: '7',
    name: 'Danish Superliga',
    code: 'DSL',
    id: '19',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/Danish_Superliga_logo.svg/1200px-Danish_Superliga_logo.svg.png',
  },
  {
    countryId: '7',
    name: 'Danish 1st Division',
    code: 'D1D',
    id: '20',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Danish_1st_Division_logo.svg/1200px-Danish_1st_Division_logo.svg.png',
  },
  {
    countryId: '7',
    name: 'Danish 2nd Division',
    code: 'D2D',
    id: '21',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Danish_2nd_Division_logo.svg/1200px-Danish_2nd_Division_logo.svg.png',
  },
  // Estonia
  {
    countryId: '8',
    name: 'Meistriliiga',
    code: 'ML',
    id: '22',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/30/Meistriliiga_logo.svg/1200px-Meistriliiga_logo.svg.png',
  },
  {
    countryId: '8',
    name: 'Esiliiga',
    code: 'EL',
    id: '23',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Esiliiga_logo.svg/1200px-Esiliiga_logo.svg.png',
  },
  {
    countryId: '8',
    name: 'Esiliiga B',
    code: 'ELB',
    id: '24',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Esiliiga_B_logo.svg/1200px-Esiliiga_B_logo.svg.png',
  },
  // Finland
  {
    countryId: '9',
    name: 'Veikkausliiga',
    code: 'VL',
    id: '25',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Veikkausliiga_logo.svg/1200px-Veikkausliiga_logo.svg.png',
  },
  {
    countryId: '9',
    name: 'Ykkönen',
    code: 'YKK',
    id: '26',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Ykk%C3%B6nen_logo.svg/1200px-Ykk%C3%B6nen_logo.svg.png',
  },
  {
    countryId: '9',
    name: 'Kakkonen',
    code: 'KAK',
    id: '27',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Kakkonen_logo.svg/1200px-Kakkonen_logo.svg.png',
  },
  // France
  {
    countryId: '10',
    name: 'Ligue 1',
    code: 'L1',
    id: '28',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Ligue_1_Uber_Eats_logo_%282020%29.svg/1200px-Ligue_1_Uber_Eats_logo_%282020%29.svg.png',
  },
  {
    countryId: '10',
    name: 'Ligue 2',
    code: 'L2',
    id: '29',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Ligue_2_BKT_logo_%282020%29.svg/1200px-Ligue_2_BKT_logo_%282020%29.svg.png',
  },
  {
    countryId: '10',
    name: 'Championnat National',
    code: 'CN',
    id: '30',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Championnat_National_logo.svg/1200px-Championnat_National_logo.svg.png',
  },
  // Germany
  {
    countryId: '11',
    name: 'Bundesliga',
    code: 'BL',
    id: '31',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Bundesliga_logo_%282017%29.svg/1200px-Bundesliga_logo_%282017%29.svg.png',
  },
  {
    countryId: '11',
    name: '2. Bundesliga',
    code: '2BL',
    id: '32',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/87/2._Bundesliga_logo_%282017%29.svg/1200px-2._Bundesliga_logo_%282017%29.svg.png',
  },
  {
    countryId: '11',
    name: '3. Liga',
    code: '3L',
    id: '33',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/3._Liga_logo.svg/1200px-3._Liga_logo.svg.png',
  },
  // Greece
  {
    countryId: '12',
    name: 'Super League Greece',
    code: 'SLG',
    id: '34',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/02/Superleague_Greece_logo.svg/1200px-Superleague_Greece_logo.svg.png',
  },
  {
    countryId: '12',
    name: 'Football League Greece',
    code: 'FLG',
    id: '35',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Football_League_Greece_logo.svg/1200px-Football_League_Greece_logo.svg.png',
  },
  {
    countryId: '12',
    name: 'Gamma Ethniki',
    code: 'GE',
    id: '36',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Gamma_Ethniki_logo.svg/1200px-Gamma_Ethniki_logo.svg.png',
  },
  // Hungary
  {
    countryId: '13',
    name: 'Nemzeti Bajnokság I',
    code: 'NB1',
    id: '37',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/Nemzeti_Bajnoks%C3%A1g_I_logo.svg/1200px-Nemzeti_Bajnoks%C3%A1g_I_logo.svg.png',
  },
  {
    countryId: '13',
    name: 'Nemzeti Bajnokság II',
    code: 'NB2',
    id: '38',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Nemzeti_Bajnoks%C3%A1g_II_logo.svg/1200px-Nemzeti_Bajnoks%C3%A1g_II_logo.svg.png',
  },
  {
    countryId: '13',
    name: 'Nemzeti Bajnokság III',
    code: 'NB3',
    id: '39',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Nemzeti_Bajnoks%C3%A1g_III_logo.svg/1200px-Nemzeti_Bajnoks%C3%A1g_III_logo.svg.png',
  },
  // Iceland
  {
    countryId: '14',
    name: 'Úrvalsdeild',
    code: 'UR',
    id: '40',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a6/%C3%9Arvalsdeild_karla_logo.svg/1200px-%C3%9Arvalsdeild_karla_logo.svg.png',
  },
  {
    countryId: '14',
    name: '1. deild karla',
    code: '1DK',
    id: '41',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/1._deild_karla_logo.svg/1200px-1._deild_karla_logo.svg.png',
  },
  {
    countryId: '14',
    name: '2. deild karla',
    code: '2DK',
    id: '42',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/23/2._deild_karla_logo.svg/1200px-2._deild_karla_logo.svg.png',
  },
  // Ireland
  {
    countryId: '15',
    name: 'League of Ireland Premier Division',
    code: 'LOIPD',
    id: '43',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/League_of_Ireland_Premier_Division_logo.svg/1200px-League_of_Ireland_Premier_Division_logo.svg.png',
  },
  {
    countryId: '15',
    name: 'League of Ireland First Division',
    code: 'LOIFD',
    id: '44',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/27/League_of_Ireland_First_Division_logo.svg/1200px-League_of_Ireland_First_Division_logo.svg.png',
  },
  {
    countryId: '15',
    name: 'League of Ireland Second Division',
    code: 'LOISD',
    id: '45',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/League_of_Ireland_Second_Division_logo.svg/1200px-League_of_Ireland_Second_Division_logo.svg.png',
  },
  // Latvia
  {
    countryId: '17',
    name: 'Virslīga',
    code: 'V',
    id: '46',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Virsl%C4%ABga_logo.svg/1200px-Virsl%C4%ABga_logo.svg.png',
  },
  {
    countryId: '17',
    name: '1. līga',
    code: '1L',
    id: '47',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/1._l%C4%ABga_logo.svg/1200px-1._l%C4%ABga_logo.svg.png',
  },
  {
    countryId: '17',
    name: '2. līga',
    code: '2L',
    id: '48',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/2._l%C4%ABga_logo.svg/1200px-2._l%C4%ABga_logo.svg.png',
  },
  // Lithuania
  {
    countryId: '18',
    name: 'A Lyga',
    code: 'AL',
    id: '49',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/A_Lyga_logo.svg/1200px-A_Lyga_logo.svg.png',
  },
  {
    countryId: '18',
    name: 'I Lyga',
    code: 'IL',
    id: '50',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2d/I_Lyga_logo.svg/1200px-I_Lyga_logo.svg.png',
  },
  {
    countryId: '18',
    name: 'II Lyga',
    code: 'IIL',
    id: '51',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/42/II_Lyga_logo.svg/1200px-II_Lyga_logo.svg.png',
  },
  // Luxembourg
  {
    countryId: '19',
    name: 'Luxembourg National Division',
    code: 'LND',
    id: '52',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/62/Luxembourg_National_Division_logo.svg/1200px-Luxembourg_National_Division_logo.svg.png',
  },
  {
    countryId: '19',
    name: 'Luxembourg Division of Honour',
    code: 'LDOH',
    id: '53',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Luxembourg_Division_of_Honour_logo.svg/1200px-Luxembourg_Division_of_Honour_logo.svg.png',
  },
  {
    countryId: '19',
    name: 'Luxembourg 1. Division',
    code: 'L1D',
    id: '54',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Luxembourg_1._Division_logo.svg/1200px-Luxembourg_1._Division_logo.svg.png',
  },
  // Malta
  {
    countryId: '20',
    name: 'Maltese Premier League',
    code: 'MPL',
    id: '55',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/Maltese_Premier_League_logo.svg/1200px-Maltese_Premier_League_logo.svg.png',
  },
  {
    countryId: '20',
    name: 'Maltese First Division',
    code: 'MFD',
    id: '56',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1d/Maltese_First_Division_logo.svg/1200px-Maltese_First_Division_logo.svg.png',
  },
  {
    countryId: '20',
    name: 'Maltese Second Division',
    code: 'MSD',
    id: '57',
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/Maltese_Second_Division_logo.svg/1200px-Maltese_Second_Division_logo.svg.png',
  },
];

export const leaguesMock: LeaguesPayload = {
  response: leagues2015,
};
