import { TeamModel, TeamPayload } from './models/index';

export const teams2015: TeamModel[] = [
  // La Liga
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3e/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png',
    id: '1',
    name: 'FC Barcelona',
    countryID: '1',
    leagueID: '1',
    code: 'FCB',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Real_Madrid_CF.svg/1200px-Real_Madrid_CF.svg.png',
    id: '2',
    name: 'Real Madrid',
    countryID: '1',
    leagueID: '1',
    code: 'RMA',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/70/Atl%C3%A9tico_Madrid_logo.svg/1200px-Atl%C3%A9tico_Madrid_logo.svg.png',
    id: '3',
    name: 'Atlético Madrid',
    countryID: '1',
    leagueID: '1',
    code: 'ATM',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Valencia_CF_logo.svg/1200px-Valencia_CF_logo.svg.png',
    id: '4',
    name: 'Valencia CF',
    countryID: '1',
    leagueID: '1',
    code: 'VAL',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Sevilla_CF_logo.svg/1200px-Sevilla_CF_logo.svg.png',
    id: '5',
    name: 'Sevilla FC',
    countryID: '1',
    leagueID: '1',
    code: 'SEV',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Real_Betis_logo.svg/1200px-Real_Betis_logo.svg.png',
    id: '6',
    name: 'Real Betis',
    countryID: '1',
    leagueID: '1',
    code: 'BET',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Athletic_Bilbao_logo.svg/1200px-Athletic_Bilbao_logo.svg.png',
    id: '7',
    name: 'Athletic Bilbao',
    countryID: '1',
    leagueID: '1',
    code: 'ATH',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Villarreal_CF_logo.svg/1200px-Villarreal_CF_logo.svg.png',
    id: '8',
    name: 'Villarreal CF',
    countryID: '1',
    leagueID: '1',
    code: 'VIL',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/RC_Celta_de_Vigo_logo.svg/1200px-RC_Celta_de_Vigo_logo.svg.png',
    id: '9',
    name: 'Celta Vigo',
    countryID: '1',
    leagueID: '1',
    code: 'CEL',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Real_Sociedad_logo.svg/1200px-Real_Sociedad_logo.svg.png',
    id: '10',
    name: 'Real Sociedad',
    countryID: '1',
    leagueID: '1',
    code: 'SOC',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Levante_UD_logo.svg/1200px-Levante_UD_logo.svg.png',
    id: '11',
    name: 'Levante UD',
    countryID: '1',
    leagueID: '1',
    code: 'LEV',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Deportivo_La_Coru%C3%B1a_logo.svg/1200px-Deportivo_La_Coru%C3%B1a_logo.svg.png',
    id: '12',
    name: 'Deportivo La Coruña',
    countryID: '1',
    leagueID: '1',
    code: 'DEP',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/M%C3%A1laga_CF_logo.svg/1200px-M%C3%A1laga_CF_logo.svg.png',
    id: '13',
    name: 'Málaga CF',
    countryID: '1',
    leagueID: '1',
    code: 'MAL',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/90/Getafe_CF_logo.svg/1200px-Getafe_CF_logo.svg.png',
    id: '14',
    name: 'Getafe CF',
    countryID: '1',
    leagueID: '1',
    code: 'GET',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ea/RCDE_Espanyol_logo.svg/1200px-RCDE_Espanyol_logo.svg.png',
    id: '15',
    name: 'Espanyol',
    countryID: '1',
    leagueID: '1',
    code: 'ESP',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Rayo_Vallecano_logo.svg/1200px-Rayo_Vallecano_logo.svg.png',
    id: '16',
    name: 'Rayo Vallecano',
    countryID: '1',
    leagueID: '1',
    code: 'RAY',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/Granada_CF_logo.svg/1200px-Granada_CF_logo.svg.png',
    id: '17',
    name: 'Granada CF',
    countryID: '1',
    leagueID: '1',
    code: 'GRA',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/26/UD_Las_Palmas_logo.svg/1200px-UD_Las_Palmas_logo.svg.png',
    id: '18',
    name: 'UD Las Palmas',
    countryID: '1',
    leagueID: '1',
    code: 'LPA',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/10/SD_Eibar_logo.svg/1200px-SD_Eibar_logo.svg.png',
    id: '19',
    name: 'SD Eibar',
    countryID: '1',
    leagueID: '1',
    code: 'EIB',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Sporting_de_Gij%C3%B3n_logo.svg/1200px-Sporting_de_Gij%C3%B3n_logo.svg.png',
    id: '20',
    name: 'Sporting de Gijón',
    countryID: '1',
    leagueID: '1',
    code: 'SPO',
  },
  // Premier League
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png',
    id: '21',
    name: 'Arsenal',
    countryID: '2',
    leagueID: '4',
    code: 'ARS',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png',
    id: '22',
    name: 'Chelsea',
    countryID: '2',
    leagueID: '4',
    code: 'CHE',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png',
    id: '23',
    name: 'Liverpool',
    countryID: '2',
    leagueID: '4',
    code: 'LIV',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png',
    id: '24',
    name: 'Manchester United',
    countryID: '2',
    leagueID: '4',
    code: 'MUN',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png',
    id: '25',
    name: 'Manchester City',
    countryID: '2',
    leagueID: '4',
    code: 'MCI',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Tottenham_Hotspur.svg/1200px-Tottenham_Hotspur.svg.png',
    id: '26',
    name: 'Tottenham Hotspur',
    countryID: '2',
    leagueID: '4',
    code: 'TOT',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/West_Ham_United_FC_logo.svg/1200px-West_Ham_United_FC_logo.svg.png',
    id: '27',
    name: 'West Ham United',
    countryID: '2',
    leagueID: '4',
    code: 'WHU',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Everton_FC_logo.svg/1200px-Everton_FC_logo.svg.png',
    id: '28',
    name: 'Everton',
    countryID: '2',
    leagueID: '4',
    code: 'EVE',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/Leicester_City_crest.svg/1200px-Leicester_City_crest.svg.png',
    id: '29',
    name: 'Leicester City',
    countryID: '2',
    leagueID: '4',
    code: 'LEI',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e2/Southampton_FC.svg/1200px-Southampton_FC.svg.png',
    id: '30',
    name: 'Southampton',
    countryID: '2',
    leagueID: '4',
    code: 'SOU',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Crystal_Palace_FC_logo.svg/1200px-Crystal_Palace_FC_logo.svg.png',
    id: '31',
    name: 'Crystal Palace',
    countryID: '2',
    leagueID: '4',
    code: 'CRY',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Swansea_City_AFC_logo.svg/1200px-Swansea_City_AFC_logo.svg.png',
    id: '32',
    name: 'Swansea City',
    countryID: '2',
    leagueID: '4',
    code: 'SWA',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Stoke_City_FC.svg/1200px-Stoke_City_FC.svg.png',
    id: '33',
    name: 'Stoke City',
    countryID: '2',
    leagueID: '4',
    code: 'STK',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c2/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png',
    id: '34',
    name: 'Newcastle United',
    countryID: '2',
    leagueID: '4',
    code: 'NEW',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/West_Bromwich_Albion.svg/1200px-West_Bromwich_Albion.svg.png',
    id: '35',
    name: 'West Bromwich Albion',
    countryID: '2',
    leagueID: '4',
    code: 'WBA',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5a/Sunderland_AFC_logo.svg/1200px-Sunderland_AFC_logo.svg.png',
    id: '36',
    name: 'Sunderland',
    countryID: '2',
    leagueID: '4',
    code: 'SUN',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Norwich_City.svg/1200px-Norwich_City.svg.png',
    id: '37',
    name: 'Norwich City',
    countryID: '2',
    leagueID: '4',
    code: 'NOR',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/67/AFC_Bournemouth_%282013%29.svg/1200px-AFC_Bournemouth_%282013%29.svg.png',
    id: '38',
    name: 'AFC Bournemouth',
    countryID: '2',
    leagueID: '4',
    code: 'BOU',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Watford.svg/1200px-Watford.svg.png',
    id: '39',
    name: 'Watford',
    countryID: '2',
    leagueID: '4',
    code: 'WAT',
  },
  {
    image: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Aston_Villa.svg/1200px-Aston_Villa.svg.png',
    id: '40',
    name: 'Aston Villa',
    countryID: '2',
    leagueID: '4',
    code: 'AVL',
  },
];

export const teamsMockList: TeamPayload = {
  response: teams2015,
};
